metadata:
  title:
    default: MIORA - Expert Shopify Development Agency
    template: '%s | MIORA'
  description: "Professional Shopify development, custom themes, speed optimization & seamless migrations. Transform your e-commerce vision into reality."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: MIORA - Shopify Experts
    type: website
    images:
      - url: '~/assets/images/og-image.png?v=2'
        width: 1200
        height: 630
  twitter:
    handle: '@arthelokyo'
    site: '@arthelokyo'
    cardType: summary_large_image